Config = {}

Config.Items = {
    -- shared
    ["x_apple"] = { ["Hunger"] = 10, ["Thirst"] = 1, ["Stress"] = -0.5 },
    ["x_baking_soda"] = nil,
    ["x_banana"] = { ["Hunger"] = 10, ["Thirst"] = -2, ["Stress"] = -0.5 },
    ["x_blueberry"] = { ["Hunger"] = 5, ["Thirst"] = 1, ["Stress"] = -0.5 },
    ["x_cheese_cheddar"] = { ["Hunger"] = 1 },
    ["x_cheese_mozzarella"] = { ["Hunger"] = 1 },
    ["x_cheese_parmesan"] = { ["Hunger"] = 1 },
    ["x_chocolate"] = { ["Hunger"] = 20, ["Thirst"] = -5, ["Stress"] = -0.5 },
    ["x_coffee_bean"] = nil,
    ["x_cream"] = { ["Hunger"] = 2, ["Stress"] = -0.5 },
    ["x_cup_empty"] = nil,
    ["x_dough"] = nil,
    ["x_dough_floured"] = nil,
    ["x_egg"] = nil,
    ["x_flour"] = nil,
    ["x_glass_empty"] = nil,
    ["x_glass_water"] = { ["Thirst"] = 20, ["Stress"] = -0.5 },
    ["x_grape"] = { ["Hunger"] = 5, ["Thirst"] = 1, ["Stress"] = -0.5 },
    ["x_hand_mixer"] = nil,
    ["x_lemon"] = { ["Hunger"] = 1, ["Thirst"] = -5 },
    ["x_lemonade"] = { ["Thirst"] = 30, ["Stress"] = -0.5 },
    ["x_lettuce"] = { ["Hunger"] = 10, ["Thirst"] = 5, ["Stress"] = -0.5 },
    ["x_lime"] = { ["Hunger"] = 1, ["Thirst"] = -5 },
    ["x_mango"] = { ["Hunger"] = 10, ["Thirst"] = 2, ["Stress"] = -0.5 },
    ["x_marshmellow"] = { ["Hunger"] = 10, ["Stress"] = -0.5 },
    ["x_milk"] = { ["Thirst"] = 30, ["Stress"] = -0.5 },
    ["x_mushroom"] = { ["Hunger"] = 2 },
    ["x_olive"] = { ["Hunger"] = 2 },
    ["x_onion"] = { ["Hunger"] = 2, ["Thirst"] = -15 },
    ["x_onion_sliced"] ={ ["Hunger"] = 2, ["Thirst"] = -15 },
    ["x_orange"] = { ["Hunger"] = 5, ["Thirst"] = 15, ["Stress"] = -0.5 },
    ["x_pickle"] = { ["Hunger"] = 1, ["Thirst"] = 1 },
    ["x_pizza_sauce"] = nil,
    ["x_potato"] = nil,
    ["x_potato_sliced"] = nil,
    ["x_rolling_pin"] = nil,
    ["x_salt"] = { ["Thirst"] = -30 },
    ["x_strawberry"] = { ["Hunger"] = 10, ["Thirst"] = 2, ["Stress"] = -0.5 },
    ["x_sugar"] = { ["Hunger"] = 1, ["Thirst"] = -5 },
    ["x_tea"] = nil,
    ["x_tomato"] = { ["Hunger"] = 5, ["Thirst"] = 5, ["Stress"] = -0.5 },
    ["x_vanilla_bean"] = nil,
    ["x_wrap"] = { ["Hunger"] = 15, ["Stress"] = -0.5 },
    
    -- catcafe
    ["x_bentobox"] = { ["Hunger"] = 40, ["Stress"] = -1 },
    ["x_boba"] = nil,
    ["x_brownie_catcafe"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_brownie_catcafe_uncooked"] = nil,
    ["x_coffee_iced_catcafe"] = { ["Thirst"] = 20, ["Stress"] = -1 },
    ["x_cookie_catcafe"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_cookie_catcafe_uncooked"] = nil,
    ["x_cupcake_catcafe"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_cupcake_catcafe_uncooked"] = nil,
    ["x_donut_catcafe"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_donut_catcafe_uncooked"] = nil,
    ["x_instant_noodles"] = { ["Hunger"] = 30, ["Thirst"] = 10, ["Stress"] = -1 },
    ["x_instant_noodles_uncooked"] = nil,
    ["x_instant_rice"] = { ["Hunger"] = 30, ["Stress"] = -1 },
    ["x_instant_rice_uncooked"] = nil,
    ["x_lolipop_catcafe"] = { ["Hunger"] = 10, ["Stress"] = -1 },
    ["x_matcha"] = nil,
    ["x_menu_catcafe"] = nil,
    ["x_mochi_blueberry"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_mochi_blueberry_uncooked"] = nil,
    ["x_mochi_matcha"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_mochi_matcha_uncooked"] = nil,
    ["x_mochi_orange"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_mochi_orange_uncooked"] = nil,
    ["x_mochi_strawberry"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_mochi_strawberry_uncooked"] = nil,
    ["x_neko_onigiri"] = { ["Hunger"] = 40, ["Stress"] = -1 },
    ["x_nori"] = nil,
    ["x_paste_miso"] = nil,
    ["x_pizza_kitty"] = { ["Hunger"] = 40, ["Stress"] = -1 },
    ["x_pizza_kitty_uncooked"] = nil,
    ["x_purrito"] = { ["Hunger"] = 40, ["Stress"] = -1 },
    ["x_purrito_uncooked"] = nil,
    ["x_ramen"] = { ["Hunger"] = 30, ["Thirst"] = 10, ["Stress"] = -1 },
    ["x_ricecake"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_sake"] = { ["Thirst"] = 20, ["Stress"] = -1 },
    ["x_sandy_chocolate"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_sandy_chocolate_uncooked"] = nil,
    ["x_sandy_vanilla"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_sandy_vanilla_uncooked"] = nil,
    ["x_soup_miso"] = { ["Hunger"] = 30, ["Thirst"] = 10, ["Stress"] = -1 },
    ["x_soup_tofu"] = { ["Hunger"] = 25, ["Thirst"] = 5, ["Stress"] = -1 },
    ["x_strawberryroll_catcafe"] = { ["Hunger"] = 20, ["Stress"] = -1 },
    ["x_strawberryroll_catcafe_uncooked"] = nil,
    ["x_sushi_catcafe"] = { ["Hunger"] = 30, ["Stress"] = -1 },
    ["x_tea_boba"] = { ["Thirst"] = 20, ["Stress"] = -1 },
    ["x_tea_boba_blueberry"] = { ["Thirst"] = 20, ["Stress"] = -1 },
    ["x_tea_boba_chocolate"] = { ["Thirst"] = 20, ["Stress"] = -1 },
    ["x_tea_boba_matcha"] = { ["Thirst"] = 20, ["Stress"] = -1 },
    ["x_tea_boba_strawberry"] = { ["Thirst"] = 20, ["Stress"] = -1 },
    ["x_tea_iced_lemon_lime"] = { ["Thirst"] = 20, ["Stress"] = -1 },
    ["x_tea_iced_orange"] = { ["Thirst"] = 20, ["Stress"] = -1 },
    ["x_tofu"] = { ["Hunger"] = 5, ["Thirst"] = 1, ["Stress"] = -1 },
}